### ISSUE TITLE
Restart Stuck if it's Crashed in a Fork

### ISSUE THREAD

**Issue by leordev** [EOSIO/demux-js-eos#17]
If demux gets crashed in a block that is being forked it fails to restart. When we try to start demux it goes to an infinite loop trying to read the current and last block (my personal logs where I write the head and each block number read): 

```
{"log":"1|demux    | Mongo Block State Header -- Block Num 17073622\n","stream":"stdout","time":"2018-09-18T14:11:26.729090615Z"}
{"log":"1|demux    | Mongo Getting blockNumber: 17073622\n","stream":"stdout","time":"2018-09-18T14:11:26.729468451Z"}
{"log":"1|demux    | Mongo Block State Header -- Block Num 17073623\n","stream":"stdout","time":"2018-09-18T14:11:27.229939692Z"}
{"log":"1|demux    | Mongo Getting blockNumber: 17073623\n","stream":"stdout","time":"2018-09-18T14:11:27.229959764Z"}
{"log":"1|demux    | Mongo Block State Header -- Block Num 17073624\n","stream":"stdout","time":"2018-09-18T14:11:27.728765716Z"}
{"log":"1|demux    | Mongo Getting blockNumber: 17073624\n","stream":"stdout","time":"2018-09-18T14:11:27.729217749Z"}
{"log":"1|demux    | Mongo Block State Header -- Block Num 17073625\n","stream":"stdout","time":"2018-09-18T14:11:28.230462666Z"}
{"log":"1|demux    | Mongo Getting blockNumber: 17073625\n","stream":"stdout","time":"2018-09-18T14:11:28.231375248Z"}
```

I suspect it is caused by the following code because `this.blockHistory.length` is zero when we are starting up demux.

```
// Continue if the new block is on the same chain as our history, or if we've just started
      if (expectedHash === actualHash || this.blockHistory.length === 0) {
```

**Comment by nicolas-simplex** [comment]
I'm having exactly the same issue. Is there a fix for this problem?

**Comment by jeffreyssmith2nd** [comment]
I believe this was fixed in a newer release, @flux627 can you confirm?

**Comment by nicolas-simplex** [comment]
@jeffreyssmith2nd this is still an issue for me in version 2.0.0. It keeps seeking the same block again and again and it never detectes the fork.
Given the reader has no access to the state I don't see how could it detect the fork anyway.

**Comment by flux627** [comment]
This should be fixed now!
